/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
/******************************************************************************
*	This file contains defines to support oscillator register initialization
*		for CY7C63310-SXC
******************************************************************************/

#define CPU_CLOCK              0x0     //CPU Clock value
#define CPU_CLOCK_MASK         0x1     //CPU Clock mask
#define CPU_CLOCK_JUST         0x0     //CPU Clock value justified

#define CPU_CLOCK_SPEED        0x3     //CPU Clock Speed value
#define CPU_CLOCK_SPEED_MASK   0x7     //CPU Clock Speed mask
#define CPU_CLOCK_SPEED_JUST   0x3     //CPU Clock Speed value justified

#define TIMER_CLOCK            0x0     //Timer Clock value
#define TIMER_CLOCK_MASK       0x3     //Timer Clock mask
#define TIMER_CLOCK_JUST       0x0     //Timer Clock value justified

#define TIMER_CLOCK_SPEED      0x0     //Timer Clock Speed value
#define TIMER_CLOCK_SPEED_MASK 0xc     //Timer Clock Speed mask
#define TIMER_CLOCK_SPEED_JUST 0x0     //Timer Clock Speed value justified

#define CAPT_CLOCK             0x0     //Capture Clock value
#define CAPT_CLOCK_MASK        0x30    //Capture Clock mask
#define CAPT_CLOCK_JUST        0x0     //Capture Clock value justified

#define CAPT_CLOCK_SPEED       0x2     //Capture Clock Speed value
#define CAPT_CLOCK_SPEED_MASK  0xc0    //Capture Clock Speed mask
#define CAPT_CLOCK_SPEED_JUST  0x80    //Capture Clock Speed value justified

#define CAPT_EDGE              0x0     //Capture Edge value
#define CAPT_EDGE_MASK         0x80    //Capture Edge mask
#define CAPT_EDGE_JUST         0x0     //Capture Edge value justified

#define CAPT_PRESCALE          0x0     //Capture Prescale value
#define CAPT_PRESCALE_MASK     0x70    //Capture Prescale mask
#define CAPT_PRESCALE_JUST     0x0     //Capture Prescale value justified

#define USB_CLOCK              0x0     //USB Clock value
#define USB_CLOCK_MASK         0x20    //USB Clock mask
#define USB_CLOCK_JUST         0x0     //USB Clock value justified

#define USB_CLOCK_SPEED        0x0     //CPU Clock Speed value
#define USB_CLOCK_SPEED_MASK   0x40    //CPU Clock Speed mask
#define USB_CLOCK_SPEED_JUST   0x0     //CPU Clock Speed value justified

#define CLOCK_OUT              0x0     //Clock Out value
#define CLOCK_OUT_MASK         0x3     //Clock Out mask
#define CLOCK_OUT_JUST         0x0     //Clock Out value justified

#define LV_DETECT_LEVEL        0x4     //Low V Detect Level value
#define LV_DETECT_LEVEL_MASK   0x7     //Low V Detect Level mask
#define LV_DETECT_LEVEL_JUST   0x4     //Low V Detect Level value justified

#define PWR_ON_RESET_LEVEL          0x1    //PowerOn Reset Level value
#define PWR_ON_RESET_LEVEL_MASK     0x30   //PowerOn Reset Level mask
#define PWR_ON_RESET_LEVEL_JUST     0x10   //PowerOn Reset Level value justified

#define WATCHDOG_ENABLE        0x0     //Watchdog Enable value

