;  Generated by PSoC Designer 5.4.3191
;
; =============================================================================
; FILENAME: PSoCConfigTBL.asm
;  
; Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
;  
; NOTES:
; Do not modify this file. It is generated by PSoC Designer each time the
; generate application function is run. The values of the parameters in this
; file can be modified by changing the values of the global parameters in the
; device editor.
;  
; =============================================================================
 
include "m8c.inc"
;  Personalization tables 
export LoadConfigTBL_pdproject1_Bank1
export LoadConfigTBL_pdproject1_Bank0
export LoadConfigTBL_pdproject1_Ordered
AREA lit(rom, rel)
LoadConfigTBL_pdproject1_Bank0:
;  Instance name USB, User Module USB
;  Global Register values Bank 0
	db		32h, 00h		; CLKIOCR register (CLKIOCR)
	db		30h, 00h		; CPUCLKCR register (CPUCLKCR)
	db		05h, 01h		; P00CR register (P00CR)
	db		06h, 01h		; P01CR register (P01CR)
	db		07h, 01h		; P02CR register (P02CR)
	db		08h, 01h		; P03CR register (P03CR)
	db		09h, 01h		; P04CR register (P04CR)
	db		0ah, 01h		; P05CR register (P05CR)
	db		0bh, 00h		; P06CR register (P06CR)
	db		0dh, 00h		; P10CR register (P10CR)
	db		0eh, 00h		; P11CR register (P11CR)
	db		0fh, 00h		; P12CR register (P12CR)
	db		10h, 00h		; P13CR register (P13CR)
	db		11h, 00h		; P14CR register (P14CR)
	db		12h, 00h		; P15CR register (P15CR)
	db		13h, 00h		; P16CR register (P16CR)
	db		3dh, 00h		; SPICR register (SPICR)
	db		2bh, 00h		; TCAPINTE register (TCAPINTE)
	db		31h, 80h		; TMRCLKCR register (TMRCLKCR)
	db		2ah, 00h		; TMRCR register (TMRCR)
	db		ffh
LoadConfigTBL_pdproject1_Bank1:
;  Instance name USB, User Module USB
;  Global Register values Bank 1
	db		e0h, 03h		; OscillatorControl_0 register (OSC_CR0)
	db		e3h, 14h		; VLDCR register (VLDCR)
	db		ffh
AREA psoc_config(rom, rel)
LoadConfigTBL_pdproject1_Ordered:
;  Ordered Global Register values
	M8C_SetBank0
	ret


; PSoC Configuration file trailer PsocConfig.asm
